name: style
on: push

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m pip install black flake8 isort
      - name: Run style checks
        run: |
          flake8 .
          black . --check
          isort .